title: "TTB: Reborn"
description: "A rebirth of Zoey's TTB for 1.16+"

github-repo: "tempestsbox/ttb"
discord-invite-code: "6TFaAuW"
curseforge-link: "minecraft/customization/ttb"


andante: "Andante"
andante-twitter: "Andantweets"
andante-github: "AndanteDevs"
andante-youtube: "channel/UC9NVFqVOj_hE6iAKxkf9kPg"

qbert: "Qbert"
qbert-twitter: "TheQbert"
qbert-github: "TinyAtomss"
qbert-youtube: "channel/UCSrZdKW3DaOfgr_qb-6M-Iw"

darkmagicsauce: "DarkMagicSauce"
# darkmagicsauce-twitter: ""
darkmagicsauce-github: "aussie-katie"
# darkmagicsauce-youtube: ""

ninja_man_0722: "Ninja_Man_0722"
# ninja_man_0722-twitter: ""
# ninja_man_0722-github: ""
# ninja_man_0722-youtube: ""

inkor_the_2nd: "iNkoR_the_2nd"
inkor_the_2nd-twitter: "iNkoR_the_2nd"
# inkor_the_2nd-github: ""
inkor_the_2nd-youtube: "channel/UC-1TC6GH9h_1RgezcpfNo5A"

thenuclearnexus: "TheNuclearNexus"
# thenuclearnexus-twitter: ""
# thenuclearnexus-github: ""
thenuclearnexus-youtube: "channel/UCegI5IfnYr2zRysbSqsr24Q"

trog: "Trog"
trog-twitter: "Dr_Trogalstaid"
# trog-github: ""
trog-youtube: "channel/UCiMiH-KIQc_8wisEIwewprg"
